// Mocks generated by Mockito 5.4.3 from annotations
// in economiza_sc/test/stores/markets_store_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:economiza_sc/models/market.dart' as _i4;
import 'package:economiza_sc/services/markets_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MarketsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMarketsService extends _i1.Mock implements _i2.MarketsService {
  @override
  _i3.Future<List<_i4.Market>> search() => (super.noSuchMethod(
        Invocation.method(
          #search,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Market>>.value(<_i4.Market>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.Market>>.value(<_i4.Market>[]),
      ) as _i3.Future<List<_i4.Market>>);
}
