name: Test Backend

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Prepare Laravel Application
      working-directory: ./backend
      run: |
        cp .env.example .env
        composer install --no-scripts
        php artisan key:generate

    - name: Run Test suite
      working-directory: ./backend
      run: php artisan test